### ISSUE TITLE
Rare chance to send GoalReached event

### ISSUE THREAD

**Issue by quantum13** [JincorTech/ico#10]
Since this condition
https://github.com/JincorTech/ico/blob/1d49cef91f29f57c9765febcf65eab4c72dc229e/contracts/JincorTokenPreSale.sol#L139
event `GoalReached` has a very rare chance to be called during transactions from real users since they will not calculate difference between current collected amount and hardCap.

Better to send back change for the last user like it done here https://github.com/kickico/contracts/blob/0ddcbc48676f0362ea80f18632bfb34d84f16e06/src/crowdsale.sol#L235

**Comment by hlogeon** [comment]
Thanks for that. But in my opinion it's kind of controversial thing.
My point of doing it just like here was the idea that if you are trying to buy exact amount of tokens and contract for some reason can not fulfil your needs - the transaction is wrong. So the question is: "Can we change the transaction amount without special user's agreement for doing that?"

**Comment by quantum13** [comment]
Ok, but you stiil need to send `GoalReached` (really? :) ). So, since real users imho won't count weis to make complete sum, you will need do this :)

**Comment by artemii235** [comment]
@quantum13 GoalReached event is removed. Thank you!
