### ISSUE TITLE
Using constants

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#27]
Consider adding keyword "constant" to the variables that do not change their values. Reading from a const variable doesn't cost any gas so this would save you some money. For example, change from this:  
  ```
string public name = "Jincor Token";
  string public symbol = "JCR";
  uint256 public decimals = 18;
  uint256 public INITIAL_SUPPLY = 35000000 * 1 ether;
```
to this:     
  ```
string public constant name = "Jincor Token";
  string public constant symbol = "JCR";
  uint256 constant  public decimals = 18;
  uint256 constant  public INITIAL_SUPPLY = 35000000 * 1 ether;
```

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
