### ISSUE TITLE
Constant functions

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#28]
Consider adding keyword "constant" to the functions that do not modify contract’s state. A constant function can tell you the result without needing a transaction. For example, add “constant” to this function:   calculateBonus()

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
