### ISSUE TITLE
Function access levels(!)

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#29]
Consider marking functions with a specific access level, for example, functions that aren't called internally, please mark with a keyword "external". Calling external function consumes less gas than public function. Also, functions that are only used internally, should be marked "internal". If you want, I can specify which modifier every function should have.
As for best practices, you should use external if you expect that the function will only ever be called externally, and use public if you also need to call this function internally.

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
