### ISSUE TITLE
Argument correctness checks

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#30]
There are some functions which do not check the correctness of passed arguments. For example, it is generally advised to always do such checks:
```
function myFunction(address _address, uint _value) {
  require(_address != address(0));
  require(_value >= 0);
  ... (other code) ...
}
```

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
