### ISSUE TITLE
Token decimals data type

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#32]
`uint256 public decimals = 18;`

The ERC20 standard specifies that decimals should be of type uint8. 
More: https://theethereum.wiki/w/index.php/ERC20_Token_Standard

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
