### ISSUE TITLE
Assert vs Requiree

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#33]
Please make sure that "assert" is used intentionally, as if it fails, all the gas is consumed. Consider replacing "assert" with "require". Require() is used for checking that the input of the function is well formated, while assert() function is used to validate contract state after making changes . Read more: https://media.consensys.net/when-to-use-revert-assert-and-require-in-solidity-61fb2c0e5a57

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
