### ISSUE TITLE
Disable ownership transfer during crowdsale

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#34]
balanceOf[msg.sender] = initialSupply;   //msg.sender gets all tokens at the beginning  
During the Crowdsale it shouldn't be possible to transfer the ownership, otherwise, it could not go well.

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
