### ISSUE TITLE
Avoid `send`

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/ico#36]
Please avoid "send" in Solidity, as there is a better alternative that is more secure. “send" does not throw an exception when not successful, make sure you deal with the failure case accordingly. Use "transfer" whenever failure of the ether transfer should rollback the whole transaction.

@pauliax
ETH address: 0xaAbf60384137D460427fD5B849017e59479797A1

**Comment by artemii235** [comment]
Hello @pauliax!

Your suggested changes were implemented. We are happy to offer you a 300 JCR bounty total for all created issues.

Thank you very much! We will be glad to consider new suggestions if you have any.
