### ISSUE TITLE
Withdraw tokens, deposited on contract address

### ISSUE THREAD

**Issue by Rapso** [JincorTech/ico#42]
It might be consider as enhancement, It happens from time to time, that users deposit their tokens on token contract address, it is good idea to have function that allows withdraw tokens.

`function withdrawTokens(address tokenaddr) onlyOwner {
ERC20 token = ERC20(tokenaddr);
uint bal = token.balance();
token.transfer(msg.sender, bal);
}`

eth address - 0xE14f7A9AF3F75a4Ccd33909B0046b16d82c6EC0e

**Comment by artemii235** [comment]
Hello @Rapso! Thank you for creating an issue. We will discuss this suggestion with team and respond you in this issue.

**Comment by artemii235** [comment]
Hello @Rapso!

We have discussed your suggestion with team and decided that `withdrawTokens` function is not required. Contributors will register at ICO panel and will be given new ETH address - they will need to move their funds to generated address and then invest from it (there is a whitelist which allows to invest only from addresses generated by our backend). We think that it will be sufficient to place **SEND ONLY ETH TO THIS ADDRESS** warning at investor's panel to prevent them from sending any tokens. Moreover we will provide wallet private key on registration so if someone sends tokens to his investor address he will be able to withdraw it manually using any ERC20 compliant wallet.

Thank you for creating this issue. We will be glad to consider new suggestions if you have any.
