### ISSUE TITLE
Multiple issues in refund function

### ISSUE THREAD

**Issue by adamkolar** [JincorTech/ico#46]
These two lines in refund function of JincorTokenPreSale contract contain three minor issues:

```    
    assert(msg.sender.send(refund));
    deposited[msg.sender] = 0;
```

1) I can't see a reason why assert is used here instead of require, considering assert doesn't refund unused gas, see: https://ethereum.stackexchange.com/questions/15166/difference-between-require-and-assert-and-the-difference-between-revert-and-thro for a guide on when to use assert/require

2) require(msg.sender.send(refund)) is practically identical to msg.sender.transfer(refund) and the latter is the current recommended way to do external calls with exception propagation

3) The order of the two lines is like a cautionary example from a textbook on how to prevent reentrancy attacks, it is true that gas stipend given to send currently protects from reentrancy, but there is no reason why the lines shouldn't be ordered in the safer way:

```    
    deposited[msg.sender] = 0;
    assert(msg.sender.send(refund));
```
and it's definitely a better practice.

**Comment by artemii235** [comment]
Hello @adamkolar!
Thank you for opening an issue.
Items 1 and 2 have been fixed already in this PR https://github.com/JincorTech/ico/pull/43 and merged to develop branch.
Item 3 is reasonable remark - we will perform required refactoring, make a decision regarding your bounty and comment it here.

**Comment by artemii235** [comment]
Hello @adamkolar!

Fix was implemented, our team is happy to offer you 400 JCR bounty for opening this issue!
