### ISSUE TITLE
Mark some variables with a keyword "constant"

### ISSUE THREAD

**Issue by pauliax** [JincorTech/ico#47]
string public name = "Jincor Token";
  string public symbol = "JCR";
  uint256 public decimals = 18;
  uint256 public INITIAL_SUPPLY = 35000000 * 1 ether;

Good practice:
Variables that do not change their value should be "constant". Reading from a const variable doesn't cost any gas so this would save you some money. 
I didn't check all the codebase, so if you decide to refactor the code, please make sure that all such variables are marked with a keyword "constant".

**Comment by hlogeon** [comment]
Hello, @pauliax 
Thanks for such an attention! I would like to tell you that those issues you already applied through our community\bounty managers was already reviewed and some of them are fixed and even bounty reward was specified.

Duplicates #27 

You can review the here: https://github.com/JincorTech/ico/issues?q=is%3Aissue+is%3Aclosed

**Comment by pauliax** [comment]
@hlogeon Sorry, my bad. Didn't notice this was posted before (I expected that the code in the repo is the latest version, with fixed previous issues). Thank you for the fast and kind response. Next time I find an issue, I will double check that it is not a duplicate 🔢

**Comment by hlogeon** [comment]
@pauliax, there is nothing to sorry about ;) It's better to have 2 duplicate issues then 1 bug in the code 😄
