### ISSUE TITLE
Concerns around using a centralised oracle for setting ETH/USD exchange rate

### ISSUE THREAD

**Issue by adamkolar** [JincorTech/ico#48]
I think getting current ETH/USD exchange rate from Kraken might be problematic, things to consider

1) bad actor in Kraken organisation can compromise your ICO by sending an incorrect exchange rate
2) flash crash event similar to that which happened on GDAX couple months ago might make your tokens unreasonably expensive for a period of time
3) a bad actor running up the price on kraken in a low volume period might use the opportunity to get the tokens for cheap

Suggestions:
1) set some limits on the variation between successive updates of the price
2) cross-check the price from multiple sources

I'm not sure how real these concerns are and since you are the first ICO I know of which does it this way, it's really hard to tell beforehand.

**Comment by hlogeon** [comment]
Hello, @adamkolar !

Thanks for creating this issue. Actually I was thinking about the case you described before but for some reason we delayed the solution.

In this case I think that the first suggestion is the best for us because it allows to set the reasonable price limits with the minimal changes and can save some gas, let's see what will @artemii235 say.

**Comment by adamkolar** [comment]
I would prefer to do it over telegram, I've already posted in your public channel, so you can contact me there.

**Comment by hlogeon** [comment]
Ok, no problem :)

**Comment by hlogeon** [comment]
@artemii235 
Any ideas about this issue?

**Comment by artemii235** [comment]
@hlogeon 
We might set some variation on price change - like 10-15% - it should be ok. We can experience issues if there are huge pumps/dumps (which happen in real and price might dramatically change even in 2 hours period) - contract will get stuck on old price if price doesn't move back. To prevent this we will have to add `setPrice` function to PriceProvider - contract owner will be able to manually adjust price in such situation.

**Comment by adamkolar** [comment]
@artemii235 
I would definitely not recommend allowing owners of the contract to set the conversion rate at will, it allows manipulation of the sale process that could make the ICO untrustworthy to buyers.

**Comment by adamkolar** [comment]
Instead, how about averaging the price over some longer period, like an hour or so, that should prevent price manipulation attacks.

**Comment by hlogeon** [comment]
What if we can try tp freeze the price if it's change was more then 15 - 20%? I mean just get the last price in this case

**Comment by adamkolar** [comment]
Problem is that if the price movement is genuine and continues in the same direction, the price will become stuck. But you can store the last "invalid" value without using it and maybe update only if the change is confirmed by following update (by staying inside the 15% limit between updates).

**Comment by hlogeon** [comment]
@adamkolar 
I like the idea, lets wait for @artemii235. He is the God of this repository ;)

**Comment by artemii235** [comment]
@adamkolar @hlogeon 
What if there is "long-term" bad actor on the exchange who keeps sending incorrect values?
1. Contract has ETH price = 300USD.
2. Then contract receives 500USD from Oracle, doesn't update price in ICO contract and keeps this incorrect value.
3. Then contract receives 500USD again. It is incorrect but contract will store it as correct value.

Regarding manual price change - ICO contract receives price from another smart contract and owner already controls the address of `PriceProvider`: https://github.com/JincorTech/ico/blob/master/contracts/JincorTokenICO.sol#L199 and there is already field for "manipulation". I think that we can't trust any 3rd party in this case but we must trust our own team :) The owner of contract might be multisig wallet and this manual adjustment will require confirmation from at least 3 persons: founders and CTO. If we even try to imagine that all these persons are bad actors - we have **many problems**  and price manipulation during ICO is the smallest one. Also if all 3 owners of multisig are compromised - price manipulation is negligible compared to another "effects".

**Comment by hlogeon** [comment]
What I think we actually need to do is to keep this issue opened for the best time. I think its nice to have a choice in such kind of questions but the priority of this task is not so high to implement it before our ICO.

**Comment by adamkolar** [comment]
The measure I'm proposing is designed to mitigates issues 2 and 3 from the OP, it's not effective in mitigating 1, that would be best mitigated by using multiple sources. But fortunately I think 1 is also the least likely attack, because reputation damage for kraken would be substantial.
It is of course at your discretion, but I think smart contracts should enforce compliance with pre-agreed terms on all sides. Especially when in your case, the softCap is enumerated in tokens sold. If you are able to change the exchange rate and therefore token price at any time, you can make the ICO end successfully independently on the amount of ETH that is raised.
