### ISSUE TITLE
Constant functions in InvestorWhiteList.sol 

### ISSUE THREAD

**Issue by tonisamja** [JincorTech/ico#50]
Functions `isAllowed` and `getReferralOf` should be declared as `constant` since they don't modify the state (read-only). Calling those functions will save gas costs.

**Comment by artemii235** [comment]
Hello @tonisamja!

Thank you for creating an issue. This is good suggestion and worth applying to our contract. We will make a decision regarding your bounty and comment it here.

It's important to mention that constant functions getting called by smart contract inside a transaction cost same amount of gas as not constant functions. It saves gas only in situation when you `call` these on your local node from client library like web3js. For more info please check this  https://ethereum.stackexchange.com/a/13855 and this https://ethereum.stackexchange.com/a/9872 threads.

**Comment by artemii235** [comment]
Hello @tonisamja!

Your suggestion was implemented. We are happy to reward you with 150 JCR tokens. Please leave your ETH address in comment to this issue and we will send you tokens when bounty distribution starts.

**Comment by tonisamja** [comment]
Hello @artemii235 
thanks and good luck!
0x79aCd9bF8D32F198eE04B5F12c013fE6eaa267Ec
