### ISSUE TITLE
Modifier canTransfer() in JincorToken.sol

### ISSUE THREAD

**Issue by tonisamja** [JincorTech/ico#51]
In [Line 87](https://github.com/JincorTech/ico/blob/3a598d88374c9e436db21502af3231718d64e5f6/contracts/JincorToken.sol#L87) you use the modifier `canTransfer()` with the var `_from`. The var should be `msg.sender` thus only transfer agents can execute this function; see also Line 82.

**Comment by artemii235** [comment]
Hello @tonisamja!

Thank you for creating an issue.
The main idea of `canTransfer` modifier is to grant permission to transfer tokens **from** selected address. Everyone who `allowed` to `transferFrom` should be able to do this so the check looks correct - this is design choice. 
I can see also that there is no standard way of doing this over the github/stack exchange so everyone is able to implement such functionality in different way according to specific requirements.

**Comment by tonisamja** [comment]
So, These `transferAgents` are allowed to move their own funds, correct?
Do these agents also have to set the allowed amount prior the call of `transferFrom`; because, StandardToken.sol requires that?

**Comment by artemii235** [comment]
@tonisamja 
Yes, if Alice is `transferAgent` she is allowed to transfer her own tokens. If she wants to allow Bob to `transferFrom` her address she must call `approve` to set the allowed amount for Bob's address.
In this case Bob can `transferFrom` Alice's tokens, but Bob still is not allowed to `transfer` his own tokens.

**Comment by tonisamja** [comment]
Thanks for clearing up @artemii235!
