### ISSUE TITLE
Referral bonus is counted towards reaching softcap/hardcap even if nobody receives it

### ISSUE THREAD

**Issue by adamkolar** [JincorTech/ico#53]
In the doPurchase function, value of referral bonus is obtained by calling calculateReferralBonus function and the tokensSold variable is incremented by this bonus, this happens whether someone actually receives the bonus or not. This means that these tokens are removed from the available tokens for sale even though no third party receives them.

```javascript  
function doPurchase() private icoActive inNormalState {
    require(!crowdsaleFinished);

    uint tokens = msg.value.mul(jcrEthRate);
    uint referralBonus = calculateReferralBonus(tokens);

    tokens = tokens.add(calculateBonus(tokens));

    uint newTokensSold = tokensSold.add(tokens).add(referralBonus);

    require(newTokensSold <= hardCap);

    if (!softCapReached && tokensSold < softCap && newTokensSold >= softCap) {
      softCapReached = true;
      SoftCapReached(softCap);
    }

    token.transfer(msg.sender, tokens);

    if (referralBonus > 0) {
      address referral = investorWhiteList.getReferralOf(msg.sender);
      if (referral != 0x0) {
        token.transfer(referral, referralBonus);
      }
    }

    collected = collected.add(msg.value);

    tokensSold = newTokensSold;

    deposited[msg.sender] = deposited[msg.sender].add(msg.value);

    NewContribution(msg.sender, tokens, msg.value);
  }
```

**Comment by artemii235** [comment]
Hello @adamkolar!

Thank you for creating an issue. Yes, it's error, we should also check if there is valid referral address before adding `bonusTokens` to `tokensSold`.

We will fix it and then post your bounty reward in comment to this issue.

**Comment by artemii235** [comment]
Hello @adamkolar!

Fix was implemented, thank you very much for opening this issue!
