### ISSUE TITLE
Saving gas in the most common operation

### ISSUE THREAD

**Issue by quantum13** [JincorTech/ico#9]
https://github.com/JincorTech/ico/blob/1d49cef91f29f57c9765febcf65eab4c72dc229e/contracts/JincorToken.sol#L32

To avoid useless wasting gas during the most common operation `transfer` after ico it is better to change order of parts in condition:
`require(released || transferAgents[_sender]); `

Checking that `released` is true is lighter operation that checking value of hashmap. After ico `released` will be always `true`, so checking `transferAgents[_sender]` in this stage is useless waste of gas.

According to https://ethereum.github.io/browser-solidity this improvement will save 331 gas per `transfer` operation

**Comment by hlogeon** [comment]
Thanks for cooperation! We will double check it and improve it in the next release

@artemii235 what do you think?

**Comment by artemii235** [comment]
@hlogeon Looks like reasonable. I will recheck gas usage in this case and fix it.

**Comment by artemii235** [comment]
@quantum13 The change was done. Thank you for your remark!
